# Generated by Django 5.1.7 on 2025-03-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER SEQUENCE users_user_id_seq RESTART WITH 10000000;",
            reverse_sql="ALTER SEQUENCE users_user_id_seq RESTART WITH 1;"
        ),
    ]
