# Generated by Django 5.1.7 on 2025-04-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='attempts',
        ),
    ]
