# Generated by Django 5.1.7 on 2025-04-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_emailverification_attempts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
