# Generated by Django 5.2 on 2025-05-02 10:33
import os

from django.contrib.auth import get_user_model
from django.db import migrations


User = get_user_model()


def create_superuser(apps, schema_editor):
    if not User.objects.filter(is_superuser=True).exists():
        User.objects.create_superuser(
            email=os.getenv('SUPERUSER_EMAIL'),
            password=os.getenv('SUPERUSER_PASSWORD'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_online_user_last_seen'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
