# Generated by Django 5.1.7 on 2025-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_data',
            field=models.JSONField(default=dict),
        ),
    ]
