# Generated by Django 5.1.7 on 2025-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_content_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actions_data',
            field=models.JSONField(default=dict),
        ),
    ]
