# Generated by Django 5.1.7 on 2025-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_actions_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
