# Generated by Django 5.1.7 on 2025-04-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='footnote',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
