# Generated by Django 5.1.7 on 2025-04-27 17:43

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0005_notification_footnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='notificatio_user_id_c291d5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('created_at__lt', datetime.datetime(2025, 4, 13, 17, 43, 51, 295580, tzinfo=datetime.timezone.utc))), fields=['created_at'], name='auto_expire_idx'),
        ),
    ]
