# Generated by Django 5.2 on 2025-04-29 07:34

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0006_notification_notificatio_user_id_c291d5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='auto_expire_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('created_at__lt', datetime.datetime(2025, 4, 15, 7, 34, 27, 278929, tzinfo=datetime.timezone.utc))), fields=['created_at'], name='auto_expire_idx'),
        ),
    ]
