# Generated by Django 5.2 on 2025-04-30 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0008_remove_notification_notificatio_user_id_c291d5_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_data',
        ),
        migrations.CreateModel(
            name='NotificationContextObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_objects', to='notifications.notification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notification', 'name'), name='unique_notification')],
            },
        ),
    ]
