# Generated by Django 5.2 on 2025-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0009_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationcontextobject',
            index=models.Index(fields=['notification'], name='notificatio_notific_5f18d9_idx'),
        ),
    ]
