# Generated by Django 5.1.7 on 2025-03-23 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=2000)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('under_review', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_votings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='VotingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=3000)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='voting.votingcomment')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting_comments', to=settings.AUTH_USER_MODEL)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='voting.voting')),
            ],
        ),
        migrations.CreateModel(
            name='VotingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.voting')),
            ],
        ),
        migrations.CreateModel(
            name='VotingOptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_choices', to=settings.AUTH_USER_MODEL)),
                ('voting_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='voting.votingoption')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voting_option', 'user'), name='unique_user_choices')],
            },
        ),
    ]
