# Generated by Django 5.1.7 on 2025-03-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
    ]
