# Generated by Django 5.2 on 2025-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20250330_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
