# Generated by Django 5.2 on 2025-06-08 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_department_projects_de_project_65e6c2_idx_and_more'),
        ('voting', '0003_voting_is_anonymous_alter_voting_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='voting',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voting',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('pending', 'На рассмотрении'), ('ended', 'Закончено')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['project'], name='voting_voti_project_cea583_idx'),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['title'], name='voting_voti_title_f859bf_idx'),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['status'], name='voting_voti_status_732e75_idx'),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['body'], name='voting_voti_body_063829_idx'),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['date_started'], name='voting_voti_date_st_f590e0_idx'),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['end_date'], name='voting_voti_end_dat_6d9172_idx'),
        ),
        migrations.AddIndex(
            model_name='votingcomment',
            index=models.Index(fields=['voting'], name='voting_voti_voting__f0c4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='votingcomment',
            index=models.Index(fields=['date_sent'], name='voting_voti_date_se_ca2899_idx'),
        ),
        migrations.AddIndex(
            model_name='votingoption',
            index=models.Index(fields=['voting'], name='voting_voti_voting__70977c_idx'),
        ),
        migrations.AddField(
            model_name='votingtag',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='voting.voting'),
        ),
        migrations.AddConstraint(
            model_name='votingtag',
            constraint=models.UniqueConstraint(fields=('voting', 'tag'), name='unique_voting_tag'),
        ),
    ]
