# Generated by Django 5.1.7 on 2025-03-23 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermissions',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='projects.role'),
        ),
    ]
