# Generated by Django 5.1.7 on 2025-04-15 18:31

import config.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_description_alter_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=config.utils.fields.WEBPField(blank=True, null=True, upload_to='projects/%Y/%m/%d/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
