# Generated by Django 5.1.7 on 2025-04-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_creator_project_owner_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
