# Generated by Django 5.1.7 on 2025-04-17 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectinvitation',
            name='unique_project_user_invitation',
        ),
        migrations.RemoveField(
            model_name='projectinvitation',
            name='status',
        ),
        migrations.AddConstraint(
            model_name='projectinvitation',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_user_invitation'),
        ),
    ]
