# Generated by Django 5.1.7 on 2025-04-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_departmentmember_memberdepartment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_project_department',
        ),
    ]
