# Generated by Django 5.2 on 2025-05-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_department_unique_project_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
        migrations.RemoveField(
            model_name='role',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rolepermissions',
            name='role',
        ),
        migrations.DeleteModel(
            name='MemberRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RolePermissions',
        ),
    ]
