# Generated by Django 5.2 on 2025-05-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projectinvitation_user'),
        ('projects', '0012_remove_role_department_remove_role_project_and_more'),
    ]

    operations = [
    ]
