# Generated by Django 5.2 on 2025-05-05 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_merge_20250502_0315'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['project'], name='projects_de_project_65e6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='memberdepartment',
            index=models.Index(fields=['user'], name='projects_me_user_id_fbbd75_idx'),
        ),
        migrations.AddIndex(
            model_name='memberdepartment',
            index=models.Index(fields=['department'], name='projects_me_departm_815105_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_pr_owner_i_dea3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_public'], name='projects_pr_is_publ_f3bb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['user'], name='projects_pr_user_id_e92369_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['project'], name='projects_pr_project_6bde3b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user'], name='projects_pr_user_id_7dfae9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project'], name='projects_pr_project_3a727c_idx'),
        ),
    ]
