# Generated by Django 5.2 on 2025-05-01 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrole',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
