# Generated by Django 5.2 on 2025-05-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_memberrole_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
