# Generated by Django 5.2 on 2025-05-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_rolepermission_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_everyone',
            field=models.BooleanField(default=False),
        ),
    ]
