# Generated by Django 5.2 on 2025-05-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_rename_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='+', to='roles.permission'),
        ),
    ]
