# Generated by Django 5.2 on 2025-05-03 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_alter_permission_codename_alter_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='memberrole',
            constraint=models.UniqueConstraint(fields=('role', 'user'), name='unique_member_role'),
        ),
    ]
