# Generated by Django 5.2 on 2025-05-03 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0011_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('codename',)},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='role',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 16, 45, 54, 739870, tzinfo=datetime.timezone.utc)),
        ),
    ]
