# Generated by Django 5.2 on 2025-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0012_alter_permission_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
