# Generated by Django 5.2 on 2025-05-03 17:24

from django.db import migrations

from roles.models import Permission
from roles.services.permissions_config import PermissionsConfig


def init_permissions(*args):
    permissions_data = PermissionsConfig.get_permissions_meta()
    permissions = []
    for codename, permission_data in permissions_data.items():
        permissions.append(
            Permission(
                codename=codename,
                name=permission_data.name,
                description=permission_data.description,
                category=permission_data.category,
                default_value=permission_data.default
            )
        )
    Permission.objects.bulk_create(
        permissions,
        update_conflicts=True,
        unique_fields=['codename'],
        update_fields=['name', 'description', 'category', 'default_value']
    )


def reset_permissions(*args):
    permissions_data = PermissionsConfig.get_permissions_meta()
    for codename in permissions_data:
        Permission.objects.filter(codename=codename).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0014_permission_default_value'),
    ]

    operations = [
        migrations.RunPython(init_permissions, reset_permissions),
    ]
