# Generated by Django 5.2 on 2025-05-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0015_init_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('-rank',)},
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='roles.role'),
        ),
    ]
