# Generated by Django 5.2 on 2025-05-03 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0016_alter_role_options_remove_role_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.permission', to_field='codename'),
        ),
    ]
