# Generated by Django 5.2 on 2025-05-05 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_department_projects_de_project_65e6c2_idx_and_more'),
        ('roles', '0017_alter_rolepermission_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memberrole',
            index=models.Index(fields=['role'], name='roles_membe_role_id_dd9a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['project'], name='roles_role_project_bdcfae_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['project', 'is_everyone'], name='roles_role_project_0e1157_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='roles_rolep_role_id_12ce19_idx'),
        ),
    ]
