# Generated by Django 5.2 on 2025-06-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_task'),
        ('roles', '0018_memberrole_roles_membe_role_id_dd9a9b_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('project', 'rank'), name='unique_role'),
        ),
    ]
