# Generated by Django 5.2 on 2025-06-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0019_role_unique_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_role',
        ),
    ]
